In [8]:
import numpy as np


def get_hankel(N):
    ret = np.zeros((N, N))
    for i in range(1, N+1):
        for j in range(1, N+1):
            ret[i-1, j-1] = 2/ ((i + j)**3 - (i + j))
    return ret

def get_toeplitz(N):
    ret = np.zeros((N, N))
    for i in range(1, N+1):
        for j in range(1, N+1):
            try:
                ret[i-1, j-1] = 2/ ((i - j + 3)*(i - j + 2)*(i - j + 1))
            except ZeroDivisionError:
                ret[i-1, j-1] = 0
    return ret

hk = get_hankel(5)
tp = get_toeplitz(5)

In [22]:
def construct_reflection(N):
    perm = np.eye(N)
    for i in range(N//2):
        temp = perm[:, -i-1].copy()
        perm[:, -i-1] = perm[:, i]
        perm[:, i] = temp
    return perm
R = construct_reflection(5)

print(hk)
print(hk @ R)
print(tp)

[[0.33333333 0.08333333 0.03333333 0.01666667 0.00952381]
 [0.08333333 0.03333333 0.01666667 0.00952381 0.00595238]
 [0.03333333 0.01666667 0.00952381 0.00595238 0.00396825]
 [0.01666667 0.00952381 0.00595238 0.00396825 0.00277778]
 [0.00952381 0.00595238 0.00396825 0.00277778 0.0020202 ]]
[[0.00952381 0.01666667 0.03333333 0.08333333 0.33333333]
 [0.00595238 0.00952381 0.01666667 0.03333333 0.08333333]
 [0.00396825 0.00595238 0.00952381 0.01666667 0.03333333]
 [0.00277778 0.00396825 0.00595238 0.00952381 0.01666667]
 [0.0020202  0.00277778 0.00396825 0.00595238 0.00952381]]
[[ 0.33333333  0.          0.          0.         -0.33333333]
 [ 0.08333333  0.33333333  0.          0.          0.        ]
 [ 0.03333333  0.08333333  0.33333333  0.          0.        ]
 [ 0.01666667  0.03333333  0.08333333  0.33333333  0.        ]
 [ 0.00952381  0.01666667  0.03333333  0.08333333  0.33333333]]


In [16]:
import torch

d_model = 6
W = torch.arange(d_model*d_model).reshape(d_model, d_model)
b = torch.arange(d_model, dtype=torch.float, requires_grad=True)
loss = torch.ones(d_model) @ (W * b) @ torch.ones(d_model)
loss.backward()
b.grad


tensor([ 90.,  96., 102., 108., 114., 120.])

In [15]:
print(W)
print(W + b)
print(loss)
print((W + b).sum())


tensor([[ 0,  1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10, 11],
        [12, 13, 14, 15, 16, 17],
        [18, 19, 20, 21, 22, 23],
        [24, 25, 26, 27, 28, 29],
        [30, 31, 32, 33, 34, 35]])
tensor([[ 0.,  2.,  4.,  6.,  8., 10.],
        [ 6.,  8., 10., 12., 14., 16.],
        [12., 14., 16., 18., 20., 22.],
        [18., 20., 22., 24., 26., 28.],
        [24., 26., 28., 30., 32., 34.],
        [30., 32., 34., 36., 38., 40.]], grad_fn=<AddBackward0>)
tensor(720., grad_fn=<DotBackward0>)
tensor(720., grad_fn=<SumBackward0>)
